from __future__ import annotations

from t4perceval.system.base import (
    EntitySystem,
    Passthrough,
    Pipeline,
    System,
    SystemContext,
    require,
    resolve_times,
)
from t4perceval.system.filter import (
    ApplyMaskSystem,
    CombineMasksSystem,
    FilterByConfidenceSystem,
    FilterByDistanceSystem,
    FilterByInstanceSystem,
    FilterByLabelSystem,
    FilterByNumPointsSystem,
    FilterByMapSystem,
    FilterByPolarGridSystem,
    FilterByRegionSystem,
    FilterBySpeedSystem,
    FilterByVisibilitySystem,
    FilterPointsByCoverageSystem,
    FilterPointsByDistanceSystem,
    FilterPointsByMapSystem,
    FilterPointsByPolarGridSystem,
    FilterPointsByRegionSystem,
    MaskSystem,
    masked_view,
)
from t4perceval.system.matching.join import MatchJoin
from t4perceval.system.matching import (
    CenterDistanceBEVMatchingSystem,
    CenterDistanceMatchingSystem,
    IoU3DMatchingSystem,
    IoUBEVMatchingSystem,
    IoURoiMatchingSystem,
    MatchingSystem,
    PlaneDistanceMatchingSystem,
)
from t4perceval.system.metric import (
    AveragePrecisionHeadingSystem,
    AveragePrecisionSystem,
    ClassificationSystem,
    ClearSystem,
    ConfusionMatrixSystem,
    CornerErrorSystem,
    HeadingFlipRateSystem,
    MeanAveragePrecisionSystem,
    MetricSystem,
    PathDisplacementSystem,
    SegmentationConfusionMatrixSystem,
    SegmentationIoUSystem,
    SegmentationMetricSystem,
)
from t4perceval.system.points import AlignPointsSystem
from t4perceval.system.preset import average_precision_sweep
from t4perceval.system.matching.threshold import Thresholds
from t4perceval.system.transform import TransformEntitySystem

__all__ = (
    "AlignPointsSystem",
    "ApplyMaskSystem",
    "AveragePrecisionHeadingSystem",
    "AveragePrecisionSystem",
    "CenterDistanceBEVMatchingSystem",
    "CenterDistanceMatchingSystem",
    "ClassificationSystem",
    "ClearSystem",
    "CombineMasksSystem",
    "ConfusionMatrixSystem",
    "CornerErrorSystem",
    "EntitySystem",
    "FilterByConfidenceSystem",
    "FilterByDistanceSystem",
    "FilterByInstanceSystem",
    "FilterByLabelSystem",
    "FilterByNumPointsSystem",
    "FilterByMapSystem",
    "FilterByPolarGridSystem",
    "FilterByRegionSystem",
    "FilterBySpeedSystem",
    "FilterByVisibilitySystem",
    "FilterPointsByCoverageSystem",
    "FilterPointsByDistanceSystem",
    "FilterPointsByMapSystem",
    "FilterPointsByPolarGridSystem",
    "FilterPointsByRegionSystem",
    "HeadingFlipRateSystem",
    "IoU3DMatchingSystem",
    "IoUBEVMatchingSystem",
    "IoURoiMatchingSystem",
    "MaskSystem",
    "MatchJoin",
    "MatchingSystem",
    "MeanAveragePrecisionSystem",
    "MetricSystem",
    "Passthrough",
    "PathDisplacementSystem",
    "Pipeline",
    "PlaneDistanceMatchingSystem",
    "SegmentationConfusionMatrixSystem",
    "SegmentationIoUSystem",
    "SegmentationMetricSystem",
    "System",
    "SystemContext",
    "Thresholds",
    "TransformEntitySystem",
    "average_precision_sweep",
    "masked_view",
    "require",
    "resolve_times",
)
